### ISSUE TITLE
Comment on your tuto "Consuming A RESTful API With Go"

### ISSUE THREAD

**Issue by arnlen** [elliotforbes/tutorialedge-rest-api#2]
First of all, thank you for [your tutorial](https://tutorialedge.net/golang/consuming-restful-api-with-go/)!

I'm creating this issue because I would like to make a suggestion on how you wrote your for loop, but I didn't find another way (comment on your website seems broken):

Your version of the *for loop*:

```go
for i := 0; i < len(responseObject.Pokemon); i++ {
  fmt.Println(responseObject.Pokemon[i].Species.Name)
}
```

I suggest to following that is - IMHO - more in the golang spirit:

```go
for _, pokemon := range responseObject.Pokemon {
  fmt.Println(pokemon.Species.Name)
}
```

I know this *for loop* was not the purpose of your tutorial, but because your tuto is the first result for Google search *"go api call"*, I think a lot of beginners (like me :) would eventually come to it.

Another detail: you should add the import `"encoding/json"` right at the beginning of the tutorial, otherwise the first execution of the code fails.

Have a nice day! 😄

**Comment by elliotforbes** [comment]
Good spot, I wonder why I did it this way originally 🤔 

I've updated the for loop, however the first code snippet doesn't rely on any json unmarshalling. The next few code snippets do so I've added a note saying this import will need to be added!

Thanks for your help @arnlen!
